name: Build and Push Image to AWS ECR (CI)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - "docker/**"
      - "app/**"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  

jobs:
  build: 
    name: Build the image and deploy it to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build Docker image
        id: build-image
        env:
          GITHUB_SHA: ${{ github.sha }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          DATABASE_URL: postgresql://dummy:dummy@localhost:5432/dummy
        run: |
          docker buildx build \
          --platform linux/amd64 \
          --load \
          --build-arg DATABASE_URL="$DATABASE_URL" \
          -f docker/Dockerfile \
          -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}" \
          .

          echo "image=${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Trivy scan (security check)
        uses: aquasecurity/trivy-action@v0.24.0
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
        

      - name: Push Docker image to ECR
        env:
          GITHUB_SHA: ${{ github.sha }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        run: |
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}"