name: CI/CD pipeline (Docker → ECR → ECS)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - "docker/**"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  ECS_TASK_DEFINITION: ${{ vars.ECS_TASK_DEFINITION }}
  

jobs:
  build: 
    name: Build the image and deploy it to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build Docker image
        id: build-image
        env:
          GITHUB_SHA: ${{ github.sha }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          DATABASE_URL: postgresql://dummy:dummy@localhost:5432/dummy
        run: |
          docker buildx build \
          --platform linux/amd64 \
          --build-arg DATABASE_URL="$DATABASE_URL" \
          -f docker/Dockerfile \
          -t "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}" \
          .

          echo "image=${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}" >> $GITHUB_OUTPUT
        

      - name: Push Docker image to ECR
        env:
          GITHUB_SHA: ${{ github.sha }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        run: |
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:${GITHUB_SHA}"


      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ecs/task_definition.json
          container-name: umami-ecs
          image: ${{ steps.build-image.outputs.image }}


      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: umami
          cluster: umami-cluster
          wait-for-service-stability: true