name: Terraform Infra & ECS Deployment (CD)

on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

  TF_VAR_db_string: ${{ secrets.DB_STRING }}
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_zone_id_cloudflare: ${{ secrets.ZONE_ID_CLOUDFLARE }}
  TF_VAR_app_image: ${{ vars.TF_VAR_app_image }}

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Terraform plan
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ env.AWS_REGION }}


      - name: terraform fmt (lint code)
        uses: dflook/terraform-fmt-check@v2
        with:
          path: infra/


      - name: terraform validate
        uses: dflook/terraform-validate@v2
        with:
          path: infra/


      - name: terraform plan
        env:
          TF_VAR_db_string: ${{ secrets.DB_STRING }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_zone_id_cloudflare: ${{ secrets.ZONE_ID_CLOUDFLARE }}
        uses: dflook/terraform-plan@v2
        with:
          path: infra/


  apply:
    runs-on: ubuntu-latest
    name: Terraform apply
    needs: plan

    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform apply
        uses: dflook/terraform-apply@v2
        with:
          path: infra/
          auto_approve: true