name: Terraform Deploy Pipeline

on: 
  workflow_dispatch:


permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for the Terraform infrastructure
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.OIDC_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: terraform plan
        uses: dflook/terraform-plan@v2
        with:
          path: infra/